### ISSUE TITLE
Logging enhancement

### ISSUE THREAD

**Issue by lordnynex** [vwochnik/jekyll-language-plugin#11]
I'm trying to switch from jekyll-multiple-languages-plugin, but I keep receiving a build exception.

```
  Liquid Exception: No language specified for current page or post. in _layouts/skeleton.html
```

I have no idea where the issue is and I'm spending a lot of time doing trial and error changes to try and fix it. It would be better if this exception was more specific about where the issue is so I can fix it and move on with my day.

**Comment by vwochnik** [comment]
Well, you can always `--trace`, then you get a more detailed exception. However, I think like I have said in #1, the issue probably is that you have omitted that `language` YAML front-matter setting. The example site is built such that every page or post must have a language setting. Otherwise `page.language` is not defined and liquid throws an exception.

**Comment by vwochnik** [comment]
As of Jekyll `3.1.2`, this is solved out of the box. However, this plugin does not yet work with that version of Jekyll.

**Comment by Odame** [comment]
@lordnynex 
Were you able to fix the issue? How did you do it? Cos here I find myself, stuck at the same error and I have no idea where the problem is, even with the --trace argument.

**Comment by vwochnik** [comment]
@Odame do you have a test repository that I can see?
