### ISSUE TITLE
Work together with Jekyll Pagination plugin

### ISSUE THREAD

**Issue by omostepaniuk** [vwochnik/jekyll-language-plugin#14]
Hi,

Is it possible to use jekyll-language-plugin in conjunction with Jekyll's pagination functionality to have links like the following:

`/en/blog/`
`/en/blog/page2/`
`/ru/blog/`
`/ru/blog/page2/`

**Comment by vwochnik** [comment]
Have you tried this already? If so, can I see the repository? Then I don't have to make up anything from scratch.

**Comment by omostepaniuk** [comment]
Hi @vwochnik

I've pushed a simple setup that I used myself to try out jekyll-language-plugin, [here it is](https://github.com/omostepaniuk/jekyll3-language-plugin-pagination). Basically, it contains a few posts in english and a couple of ones in russian. Jekyll pagination has been configured according to this documentation [chapter](http://jekyllrb.com/docs/pagination/#enable-pagination).

I set `paginate_path` variable to have posts listing paginated under `/blog`. Following the pagination docs I now have to create `/blog/index.html` page which will be translated by the engine (language prefixes are skipped) into the following directory structure
`_site/blog/index.html`
`_site/blog/page2/index.html`
`...`
`_site/blog/pageN/index.html`

As a result there is only `/en/blog/index.html` page which contains correct number of posts in listing (i.e. 5 with a given configuration) but no `/en/blog/pageN/index.html` gets generated

**Comment by vwochnik** [comment]
The reason this will probably not work out at all is that my plugin diversifies pages and posts before any generator is ran. Also, since you have to define a pagination template and that template is diversified into the English and Russion version before `jekyll-paginate` is ran, at least one of those is not rendered.

Instead of pagination, I recommend a blog `index.html` page with say top 10 posts and an `archive.html` with all posts summarized. For the archive page, you could use infinite scroll for example.

**Comment by omostepaniuk** [comment]
Ok, I got your point. 
Thank you
