### ISSUE TITLE
Conditional translations - possible?

### ISSUE THREAD

**Issue by kropsi** [vwochnik/jekyll-language-plugin#28]
Is there a way to detect if the translation string exists:

```
{% unless t 'title' %}
{{ site.title }}
{% endunless %}
```

Is there a way to assign a translated string to a parameter?

```
{% assign title = t 'title' %}
{% if title }
{{ title }}
{% else %}
{{ site.title }}
{% endif %}
```
There are other more xomplex examples where it will be useful to use or reuse translations on the page, using a varialble.

**Comment by vwochnik** [comment]
No way to check for existence of keys yet. I don't see the use case as the list of translations is known. Maybe you can check if a custom `title` has been set in the front-matter and only otherwise use the `title` translation like you have shown in the other issue.

But you can assign a translation to a variable:

```
{% capture title %}{% t 'title' %}{% endcapture %}
```

After you have done that you can use that variable inside an `if` statement to check if its empty:

```
<title>{% if title %}{{ title }}{% else %}{% t 'site.title' %}{% endif %}</title>
```
