### ISSUE TITLE
SEO improvements for generated URLs (filename/permalink)

### ISSUE THREAD

**Issue by escapedcat** [vwochnik/jekyll-language-plugin#5]
As you told [here, the created filename is based on the name of the file I create in the root folder of the project](https://github.com/vwochnik/jekyll-language-plugin/issues/3#issuecomment-163298564).

For example **about.html** will create:
`/en/about.html`
`/de/about.html`

Form an SEO point of view this would be nicer if the generated file could use a _slug_ from the lang _subset_.

For a simple page this isn't a big deal, but if you want to optimise for a certain word/product/service this would be important. For example:
`/en/hauskeeping-in-uk.html`
`/de/hausreinigung-in-deutschland.html`

On the other hand this might be too complex when it comes to posts.
Maybe this is getting out of scope now... but I wanted to bring this up. What do you think?

**Comment by vwochnik** [comment]
@escapedcat you are correct. Source file names are being used for destination file names, just as the standard Jekyll would. [This class](https://github.com/vwochnik/jekyll-language-plugin/blob/master/lib/jekyll/language_page.rb) simply prepends the language prefix to the URL by changing the URL template and making a `:language` placeholder available which could even be used in permalinks. From my viewing, it would be of considerate effort to modify Jekyll just to use language in URLs since this would imply a dynamic URL placeholder such as `:t.alias` and the language data has to be queried within the page class.

In my honest opinion, just go with this:

`/en/housekeeping-in-uk.html` <-- Your page for the UK
`/de/housekeeping-in-uk.html` <-- Optional translation (you may want later)
`/en/housekeeping-in-de.html` <-- Optional translation (you may want later)
`/de/housekeeping-in-de.html` <-- Your page for Germany

**Comment by escapedcat** [comment]
That's a misunderstanding.
My two example pages should be the same page, but with a different name.
Better example maybe would be:
`/en/best-sound-with-sony.html`
`/de/bester-klang-dank-sony.html`

In this case it would be important that _sound_ and _sony_ are recognised by search-engines in the correct language context.

Or regarding to my other example:
`/en/hauskeeping-in-germany.html`
`/de/hausreinigung-in-deutschland.html`

But I get your point that this is not what Jekyll was done for in the first place and it's too much effort to change this.
Still an awesome plugin!

**Comment by vwochnik** [comment]
Well, I'm already working on a solution. If a page or a post has a `subset` and a `language` defined upon initialization, the url placeholders will be extended by the language subset where each key is prepended by `t.`. So if you have a `slug` key within that language subset, you can access that in your permalink by `:t.slug`. It's not finished yet but I hope I can bring that.

**Comment by escapedcat** [comment]
Dude, you're awesome!
I feel pretty embarrassed asking you for all this stuff already...

**Comment by vwochnik** [comment]
Currently it is not working. But it later may work in a future version.

**Comment by vwochnik** [comment]
Anyways, you can always ask. If you have any further ideas of improvements, don't hesitate! How do you like it so far?

**Comment by vwochnik** [comment]
Feature is implemented b29f9882ee8cbbbe775e24f447f8c9c5f863f076.

Add this to your page front-matter you want to have translated URLs:

```
permalink: /:language/:t.slug:output_ext
```

And then add a `slug` key to the page subset for every translation. Look [here](https://github.com/vwochnik/jekyll-language-plugin/wiki/YAML-front-matter).

**Comment by escapedcat** [comment]
Sorry for the late reply.
Works great, thanks for your efforts!
