### ISSUE TITLE
Unifying languages plugins

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vwochnik/jekyll-language-plugin#7]
Hi @vwochnik,

there's other language plugins for Jekyll around, and maybe you may want to unify them into a better plugin.

Here's the other plugins you may be interested in:
- [jekyll-multiple-languages](https://github.com/liaohuqiu/jekyll-multiple-languages) (Might not work with Jekyll 3)
- [polyglot](https://github.com/untra/polyglot)
- [jekyll-multiple-languages-plugin](https://github.com/screeninteraction/jekyll-multiple-languages-plugin)

There's even more language plugins, but those are the ones with recent changes.

**Comment by vwochnik** [comment]
I've seen them and IMO this plugin far outperforms the plugins you have named. If you have any feature request, please open another issue.

**Comment by Anthony-Gaudino** [comment]
@vwochnik thanks for the fast reply!

I agree that your plugin is great, but there's some features on the [Polyglot](https://github.com/untra/polyglot) plugin that your plugin don't have, for example, automatic url relativization.

**Comment by vwochnik** [comment]
I haven't looked at it in great detail I admit. Please make an example of _automatic url relativization_.

**Comment by Anthony-Gaudino** [comment]
From the Polyglot README.md:

#### Relativized Local Urls

No need to meticulously manage anchor tags to link to your correct language. Polyglot modifies how pages get written to the site so your _french_ links keep vistors on your _french_ blog.

``` md
---
title: au sujet de notre entreprise
permalink: /about/
lang: fr
---
Nous sommes un restaurant situé à Paris . [Ceci est notre menu.](/menu/)
```

becomes

``` html
<header class="post-header">
  <h1 class="post-title">au sujet de notre entreprise</h1>
</header>

<article class="post-content">
  <p>Nous sommes un restaurant situé à Paris . <a href="/fr/menu/">Ceci est notre menu.</a></p>
</article>
```

Voila!

Even if you are falling back to `default_lang` page, relative links built on the _french_ site will
still link to _french_ pages.

---

## Features

This plugin stands out from other I18n Jekyll plugins.
- automatically corrects your relative links, keeping your _french_ vistors on your _french_ website, even when content has to fallback to the `default_lang`.
- builds all versions of your website _simultaneously_, allowing websites to scale efficiently.
- ...

---

So the main features that different Polyglot are the automatic relative links and the multi-threaded website generation which builds the website faster.

The other plugins I listed may have some bits that could be useful too.

**Comment by vwochnik** [comment]
My plugin does not modify `Jekyll::Site` in order to achieve multithreading and it won't since that would be too complex and the implementation of polyglot is entirely different then mine.

Concerning relative URLs: Jekyll 3.0 dropped support for relative permalinks. However, you can just use relative links in your HTML and it will work. Read the wiki page about [URLs and permalinks](https://github.com/vwochnik/jekyll-language-plugin/wiki/YAML-front-matter#urls-and-permalinks). As a sidenote, the polyglot relative URL implementation only works by virtue of a regex which only matches `href` attributes.

Pages and documents that are not being rendered for a given language, i.e. do not have the language in their YAML front-matter, are simply not available within that language. There is no fallback or default language. However, you can access all pages in all languages from your Liquid templating.

**Comment by Anthony-Gaudino** [comment]
Thank you for the info @vwochnik.

I really like that you are working hard on this plugin.

I think I will use it in a project I'm working on and when finished you will be able to add it as an example website using your plugin.

Cheers!

**Comment by vwochnik** [comment]
@Anthony-Gaudino Thank you! Look into the example site I have provided first.

**Comment by espen** [comment]
@vwochnik is it possible to link to a localized URL when using the setup as described [on the wiki](https://github.com/vwochnik/jekyll-language-plugin/wiki/YAML-front-matter#urls-and-permalinks)? Using link doesn't work as described in #32
